### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by vbuzivskoy** [hexlet-components/projects-frontend-l4-server#27]
Tests that include 'buildUrl' function fail on Windows OS. The problem is that path.join returns string with escape characters, but fastify can't parse it correctly. Therefore fastify can't find right route and returns 404 code.

**Comment by corsicanec82** [comment]
Thank you. Fixed.
Now there should be no problems with building urls on Windows.
https://github.com/hexlet-components/projects-frontend-l4-server/commit/079856a2be7fbf575b99a91245fd8614a00861e4
